### ISSUE TITLE
Polymorphic expression cannot be instantiated to expected type

### ISSUE THREAD

**Issue by satybald** [tuxdna/play-oauth2-server#3]
It's look like that authorize method doesn't work with DBAction. I have the following error:

```
! @6jl950i9h - Internal server error, for (POST) [/oauth2/access_token] ->

play.PlayExceptions$CompilationException: Compilation error[polymorphic expression cannot be instantiated to expected type;
 found   : [A]play.api.mvc.Result
 required: play.api.mvc.SimpleResult]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
[warn] play - No application found at invoker init
```

when I'm executing following code:

```
object CityAPI  extends Controller with OAuth2Provider {
  def findById(id: Long) = DBAction { implicit rs =>
    authorize(new OAuthDataHandler()) { authInfo =>
      Ok
    }
  }
}
```

**Comment by tuxdna** [comment]
Here DBAction returns `SimpleResult`, however `authorize`  returns `Result`. Since `Ok` is a valid `SimpleResult` you can use the dirty trick of `asInstanceOf` 

```
  def findById(id: Long) = DBAction { implicit rs =>
    val result: Result = authorize(new OAuthDataHandler()) { authInfo =>
      Ok
    }
    result.asInstanceOf[SimpleResult]
  }
```

A proper fix would be to make DBAction return `Result` type instead of `SimpleResult`.
